---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:latest
provisioner:
  name: ansible
scenario:
  ephemeral_directory: /tmp/molecule/curl/.molecule
verifier:
  name: ansible # if the tests are represented by the verify.yml
  options:
    v: 1