---
# tasks file for start_nginx
- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "install nginx"
  apt:
    name: ['nginx']
    state: latest

- name: Install cURL
  become: true
  package: name=curl state=present

- name: "create www directory"
  file:
    path: /var/www/{{ domain }}
    state: directory
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: copy nginx site.conf
  template:
    src: ../templates/site.conf.j2
    dest: /etc/nginx/sites-enabled/{{ domain }}
    owner: root
    group: root
    mode: '0644'

- name: "sync website"
  copy:
    src: ../files/site/
    dest: /var/www/{{ domain }}

- name: Start Nginx
  service:
    name: nginx
    state: started